import mongoose from "mongoose";
import User from "../models/User.js";
import Medicine from "../models/Medicine.js";
import { findLocality } from "./localityConstants.js";
import { calculateSuggestedPrice } from "../services/pricingService.js";

const SEED_MEDICINES = [
  {
    medicineName: "Paracetamol Tablets IP",
    brandName: "Crocin 500 Advance",
    company: "GlaxoSmithKline (GSK)",
    genericName: "Paracetamol (500mg)",
    strength: "500 mg",
    dosageForm: "Tablet",
    category: "Pain & Fever",
    quantity: 15,
    unit: "Tablets (1.5 strips)",
    price: 0,
    listingType: "free_donation",
    targetBeneficiary: "Local Old Age Home",
    originalMrp: 48,
    expiryDate: new Date("2027-04-30"),
    batchNumber: "GSK-P2409",
    packageCondition: "Intact Sealed Blister Pack",
    isPrescriptionRequired: false,
    status: "approved",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    description: "100% Free Community Donation: Unused, unexpired Paracetamol 500mg tablets stored in dry conditions below 25°C. Sealed blister packaging with clearly legible batch number and expiry date.",
    storageCondition: "Store in a cool, dry place away from sunlight (<25°C)",
    locality: "Katraj",
    pinCode: "411046",
    handoverPoint: "Bharati Vidyapeeth Main Gate / Katraj Old Age Desk",
    handoverRadiusKm: 5,
    locationCoordinates: { latitude: 18.4529, longitude: 73.8652 },
    suggestedCommunityPrice: 0,
    pricingRationale: "100% Free Community Donation dedicated to local elderly care and low-income community members.",
  },
  {
    medicineName: "Dolo 650 Tablets",
    brandName: "Dolo 650",
    company: "Micro Labs Ltd.",
    genericName: "Paracetamol IP (650mg)",
    strength: "650 mg",
    dosageForm: "Tablet",
    category: "Pain & Fever",
    quantity: 20,
    unit: "Tablets (2 strips)",
    price: 0,
    listingType: "free_donation",
    targetBeneficiary: "General Community",
    originalMrp: 72,
    expiryDate: new Date("2027-08-31"),
    batchNumber: "ML-650X82",
    packageCondition: "Intact Sealed Blister Pack",
    isPrescriptionRequired: false,
    status: "approved",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=600&q=80",
    description: "100% Free Donation: Genuine Dolo 650mg strips from a doctor-prescribed recovery course. Surplus sealed tablets kept in original foil packaging.",
    storageCondition: "Protect from moisture and direct light",
    locality: "Kothrud",
    pinCode: "411038",
    handoverPoint: "Vanaz Metro Station Entrance",
    handoverRadiusKm: 5,
    locationCoordinates: { latitude: 18.5074, longitude: 73.8077 },
    suggestedCommunityPrice: 0,
    pricingRationale: "100% Free Verified Community Medicine Donation.",
  },
  {
    medicineName: "Azithromycin Tablets IP 500mg",
    brandName: "Azee 500",
    company: "Cipla Ltd.",
    genericName: "Azithromycin Dihydrate (500mg)",
    strength: "500 mg",
    dosageForm: "Tablet",
    category: "Antibiotics",
    quantity: 6,
    unit: "Tablets (2 packs of 3)",
    price: 0,
    listingType: "free_donation",
    targetBeneficiary: "Community Health Center",
    originalMrp: 135,
    expiryDate: new Date("2027-02-28"),
    batchNumber: "CP-AZ7712",
    packageCondition: "Intact Sealed Blister Pack",
    isPrescriptionRequired: true,
    status: "approved",
    image: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?auto=format&fit=crop&w=600&q=80",
    description: "100% Free Donation: Unopened Azee 500mg antibiotic tablets. Fully sealed foil packs with clear manufacturer batch stamping and QR code.",
    storageCondition: "Store below 30°C in a dry location",
    locality: "Hinjewadi",
    pinCode: "411057",
    handoverPoint: "Phase 1 Infosys Circle",
    handoverRadiusKm: 10,
    locationCoordinates: { latitude: 18.5913, longitude: 73.7389 },
    suggestedCommunityPrice: 0,
    pricingRationale: "100% Free Verified Community Medicine Donation.",
  },
  {
    medicineName: "Vitamin C Chewable Tablets",
    brandName: "Limcee 500mg Orange",
    company: "Abbott Healthcare",
    genericName: "Ascorbic Acid IP (500mg)",
    strength: "500 mg",
    dosageForm: "Tablet",
    category: "Vitamins & Supplements",
    quantity: 30,
    unit: "Tablets (2 strips)",
    price: 0,
    listingType: "free_donation",
    targetBeneficiary: "General Community",
    originalMrp: 55,
    expiryDate: new Date("2027-10-31"),
    batchNumber: "ABT-LC901",
    packageCondition: "Intact Sealed Blister Pack",
    isPrescriptionRequired: false,
    status: "approved",
    image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=600&q=80",
    description: "100% Free Donation: Sealed strips of Limcee chewable vitamin C supplements. Surplus unexpired stock.",
    storageCondition: "Store below 25°C in cool environment",
    locality: "Baner",
    pinCode: "411045",
    handoverPoint: "High Street Starbucks Junction",
    handoverRadiusKm: 5,
    locationCoordinates: { latitude: 18.5590, longitude: 73.7868 },
    suggestedCommunityPrice: 0,
    pricingRationale: "100% Free Verified Community Medicine Donation.",
  },
  {
    medicineName: "Telmisartan Tablets IP 40mg",
    brandName: "Telma 40",
    company: "Glenmark Pharmaceuticals",
    genericName: "Telmisartan (40mg)",
    strength: "40 mg",
    dosageForm: "Tablet",
    category: "Cardiovascular & BP",
    quantity: 28,
    unit: "Tablets (2 full strips)",
    price: 0,
    listingType: "free_donation",
    targetBeneficiary: "Elderly Care Center",
    originalMrp: 210,
    expiryDate: new Date("2027-06-30"),
    batchNumber: "GM-TL409",
    packageCondition: "Intact Sealed Blister Pack",
    isPrescriptionRequired: true,
    status: "approved",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    description: "100% Free Donation: Prescription blood pressure medication. Patient dosage was altered by cardiologist, leaving 2 sealed unexpired strips.",
    storageCondition: "Store at room temperature (15-30°C)",
    locality: "Viman Nagar",
    pinCode: "411014",
    handoverPoint: "Phoenix Marketcity Gate 2",
    handoverRadiusKm: 5,
    locationCoordinates: { latitude: 18.5679, longitude: 73.9143 },
    suggestedCommunityPrice: 0,
    pricingRationale: "100% Free Verified Community Medicine Donation.",
  },
  {
    medicineName: "Metformin Hydrochloride Prolonged-Release",
    brandName: "Glycomet-GP 1",
    company: "USV Private Limited",
    genericName: "Metformin (500mg) + Glimepiride (1mg)",
    strength: "500mg / 1mg",
    dosageForm: "Tablet",
    category: "Diabetes Care",
    quantity: 20,
    unit: "Tablets (2 strips)",
    price: 0,
    listingType: "free_donation",
    targetBeneficiary: "Charitable Clinic",
    originalMrp: 165,
    expiryDate: new Date("2027-05-31"),
    batchNumber: "USV-GL044",
    packageCondition: "Intact Sealed Blister Pack",
    isPrescriptionRequired: true,
    status: "approved",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=600&q=80",
    description: "100% Free Donation: Diabetes management therapy. Genuine strips stored in a temperature-controlled household medicine cabinet.",
    storageCondition: "Keep away from excessive heat and humidity",
    locality: "Swargate",
    pinCode: "411042",
    handoverPoint: "Swargate ST Bus Stand Gate",
    handoverRadiusKm: 5,
    locationCoordinates: { latitude: 18.5018, longitude: 73.8636 },
    suggestedCommunityPrice: 0,
    pricingRationale: "100% Free Verified Community Medicine Donation.",
  },
  {
    medicineName: "Montelukast & Levocetirizine Tablets",
    brandName: "Montair LC",
    company: "Cipla Ltd.",
    genericName: "Montelukast (10mg) + Levocetirizine (5mg)",
    strength: "10mg / 5mg",
    dosageForm: "Tablet",
    category: "Respiratory & Allergy",
    quantity: 10,
    unit: "Tablets (1 strip)",
    price: 0,
    listingType: "free_donation",
    targetBeneficiary: "General Community",
    originalMrp: 180,
    expiryDate: new Date("2027-03-31"),
    batchNumber: "CP-ML310",
    packageCondition: "Intact Sealed Blister Pack",
    isPrescriptionRequired: true,
    status: "approved",
    image: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?auto=format&fit=crop&w=600&q=80",
    description: "100% Free Donation: Allergy relief tablets. Surplus from seasonal prescription in pristine sealed packaging.",
    storageCondition: "Protect from light and moisture",
    locality: "Hadapsar",
    pinCode: "411028",
    handoverPoint: "Magarpatta South Gate",
    handoverRadiusKm: 5,
    locationCoordinates: { latitude: 18.5089, longitude: 73.9259 },
    suggestedCommunityPrice: 0,
    pricingRationale: "100% Free Verified Community Medicine Donation.",
  },
  {
    medicineName: "Pantoprazole Gastro-Resistant Tablets IP",
    brandName: "Pan 40",
    company: "Alkem Laboratories",
    genericName: "Pantoprazole Sodium (40mg)",
    strength: "40 mg",
    dosageForm: "Tablet",
    category: "Gastrointestinal",
    quantity: 15,
    unit: "Tablets (1.5 strips)",
    price: 0,
    listingType: "free_donation",
    targetBeneficiary: "General Community",
    originalMrp: 130,
    expiryDate: new Date("2027-09-30"),
    batchNumber: "ALK-PN882",
    packageCondition: "Intact Sealed Blister Pack",
    isPrescriptionRequired: false,
    status: "approved",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    description: "100% Free Donation: Gastro-resistant acid reducer tablets. Intact sealed blister strips with valid manufacturer hologram.",
    storageCondition: "Store in a dry place (<25°C)",
    locality: "Wakad",
    pinCode: "411057",
    handoverPoint: "Dharmaraj Chowk",
    handoverRadiusKm: 5,
    locationCoordinates: { latitude: 18.5987, longitude: 73.7663 },
    suggestedCommunityPrice: 0,
    pricingRationale: "100% Free Verified Community Medicine Donation.",
  },
];

export const seedInitialMedicines = async () => {
  try {
    // Check if medicines exist
    const medicineCount = await Medicine.countDocuments();
    
    // Find or create default community donor user
    let donor = await User.findOne({ email: "community.donor@medisave.org" });
    if (!donor) {
      donor = await User.create({
        name: "Community Health Donor",
        email: "community.donor@medisave.org",
        password: "MedisaveSeedPassword2026!",
        phone: "+91 98230 45678",
        address: "Kothrud, Pune, Maharashtra",
        role: "user",
        isVerified: true,
      });
    }

    // Find or create default verified partner organization
    let demoPartner = await User.findOne({ email: "partner@medisave.org" });
    if (!demoPartner) {
      demoPartner = await User.create({
        name: "Demo Charitable Health Center",
        email: "partner@medisave.org",
        password: "MedisavePartner2026!",
        phone: "+91 98230 11223",
        address: "Katraj, Pune, Maharashtra",
        role: "partner",
        organizationName: "Pune Community Care Clinic",
        organizationType: "Charitable Clinic",
        locality: "Katraj",
        partnerStatus: "verified",
        isVerified: true,
      });
      console.log("Demo verified partner seeded: partner@medisave.org");
    }

    // Find or create default platform administrator / coordinator
    let admin = await User.findOne({ email: "admin@medisave.org" });
    if (!admin) {
      admin = await User.create({
        name: "PICT CEP Coordinator",
        email: "admin@medisave.org",
        password: "MedisaveAdmin2026!",
        phone: "+91 98230 99999",
        address: "PICT Campus, Dhankawadi, Pune",
        role: "admin",
        isVerified: true,
      });
      console.log("Admin coordinator seeded: admin@medisave.org");
    }

    // Only ensure administrative / system accounts exist
    // Do NOT automatically seed dummy medicines; all listings must be genuine submissions by community donors.
  } catch (error) {
    console.warn("System account verification notice:", error.message);
  }
};
